name: Deploy NextJS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync files to server
        run: |
          rsync -av --delete ./ /var/www/nextjs-app/

      - name: Build image & restart container
        run: |
          cd /var/www/nextjs-app
          docker compose down || true
          docker compose build
          docker compose up -d
