name: Deploy NextJS App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create project directory
        run: |
          mkdir -p /var/www/nextjs-app

      - name: Copy project files
        run: |
          rsync -av --delete ./ /var/www/nextjs-app/

      - name: Build and run container
        run: |
          cd /var/www/nextjs-app
          docker compose down
          docker compose build
          docker compose up -d
